CREATE TABLE product(
	productId VARCHAR2(50) PRIMARY KEY,
	pname VARCHAR2(50) NOT NULL,
	unitPrice NUMBER DEFAULT 0 NOT NULL,
	description VARCHAR2(2000) NOT NULL,
	manufacturer VARCHAR2(50) NOT NULL,
	category VARCHAR2(50) NOT NULL,
	unitsInStock NUMBER DEFAULT 0 NOT NULL,
	condition VARCHAR2(50) NOT NULL,
	ofile VARCHAR2(200),
	sfile VARCHAR2(30),
	quantity NUMBER DEFAULT 0 NOT NULL
	orderCount NUMBER DEFAULT 0 NOT NULL
);